core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('api/v1/auth/', include('authentication.urls')),

    path('', views.home, name="home"),
    path('', include('projects.urls')),
    path('', include('documents.urls')),
    path('', include('tasks.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    path('projects/new/', views.ProjectCreateView.as_view(), name='project_create'),
    path('projects/<int:pk>/detail/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:pk>/update/', views.ProjectUpdateView.as_view(), name='project_update'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),

    path('projects/<int:pk>/new-member/', views.ProjectMemberCreateView.as_view(), name='project_member_create'),
    path('projects/update-member/<int:pk>/', views.ProjectMemberUpdateView.as_view(), name='project_member_update'),
    path('projects/delete-member/<int:pk>/', views.ProjectMemberDeleteView.as_view(), name='project_member_delete'),

    path('projects/<int:pk>/new-comment/', views.ProjectCommentCreateView.as_view(), name='project_comment_create'),
    path('projects/update-comment/<int:pk>/', views.ProjectCommentUpdateView.as_view(), name='project_comment_update'),
    path('projects/delete-comment/<int:pk>/', views.ProjectCommentDeleteView.as_view(), name='project_comment_delete'),

    path('projects/<int:pk>/new-task/', views.ProjectTaskCreateView.as_view(), name="project_task_create"),


    path('api/v1/projects/', views.ProjectListCreateAPIView.as_view(), name='project_list_create_api'),
    path('api/v1/projects/<int:pk>/', views.ProjectRetrieveUpdateDestroyAPIView.as_view(), name='project_retrieve_update_destroy_api'),

    path('api/v1/projects/new-member/', views.ProjectMemberCreateAPIView.as_view(), name='projectmember_create_api'),
    path('api/v1/projects/new-comment/', views.ProjectCommentCreateAPIView.as_view(), name='projectcomment_create_api'),
    path('api/v1/projects/members/<int:pk>/', views.ProjectMemberRetrieveUpdateDestroyAPIView.as_view(), name='projectmember_retrieve_update_destroy_api'),
    path('api/v1/projects/comments/<int:pk>/', views.ProjectCommentRetrieveUpdateDestroyAPIView.as_view(), name='projectcomment_retrieve_update_destroy_api'),

    path('api/v1/projects/<int:pk>/logs/', views.ProjectLogListAPIView.as_view(), name='projectlog_list_api')
]

projects/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils import timezone
from django.contrib.auth.models import User
from documents.models import Document
from core import constants


class Project(models.Model):
    title = models.CharField(max_length=500)
    description = models.TextField(blank=True, null=True)
    documents = models.ManyToManyField(Document, related_name='projects', blank=True)
    priority = models.CharField(max_length=50, choices=constants.PRIORITY_CHOICES)
    status = models.CharField(max_length=50, choices=constants.STATUS_CHOICES)
    deadline = models.DateField(validators=[
        MinValueValidator(timezone.now().date(), 'A data de término deve ser maior que a data atual.')
    ])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = [
            models.Case(
                models.When(status='DONE', then=models.Value(1)),
                models.When(status='TO_DO', then=models.Value(0)),
                models.When(status='PAUSED', then=models.Value(0)),
                models.When(status='DEVELOPING', then=models.Value(0)),
                output_field=models.IntegerField(),
            ), 'deadline', 'title']

    def __str__(self):
        return self.title


class ProjectMember(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="projects")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="members")
    role = models.CharField(max_length=50, choices=constants.ROLE_CHOICES)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'project'], name='unique_user_project')
        ]
        ordering = [models.Case(
            models.When(role='ADMIN', then=0),
            models.When(role='MEMBER', then=1),
            default=2,
            output_field=models.IntegerField()
        )]

    def __str__(self):
        return self.user.username


class ProjectComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="project_comments")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.author.username


class ProjectLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="project_logs")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="logs")
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.project.title

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.utils import timezone
from projects.models import Project
from core import constants


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="tasks")
    responsible_people = models.ManyToManyField(User, related_name="tasks", blank=True)
    title = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    priority = models.CharField(max_length=50, choices=constants.PRIORITY_CHOICES)
    status = models.CharField(max_length=50, choices=constants.STATUS_CHOICES)
    deadline = models.DateField(validators=[
        MinValueValidator(timezone.now().date(), 'A data de término deve ser maior que a data atual.')
    ])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = [
            models.Case(
                models.When(status='DONE', then=models.Value(1)),
                models.When(status='TO_DO', then=models.Value(0)),
                models.When(status='PAUSED', then=models.Value(0)),
                models.When(status='DEVELOPING', then=models.Value(0)),
                output_field=models.IntegerField(),
            ), 'deadline', 'title']

    def __str__(self):
        return self.title

projects/views.py
import json
from django.db.models import Q, OuterRef, Subquery
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.views import View
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from rest_framework import generics
from rest_framework.permissions import SAFE_METHODS, IsAuthenticated, AllowAny
from rest_framework.exceptions import ValidationError
from core.permissions import DenyAny
from tasks.models import Task
from tasks.forms import TaskForm
from .models import Project, ProjectMember, ProjectComment
from .forms import ProjectForm, ProjectMemberForm
from . import serializers


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    context_object_name = 'projects'
    template_name = 'project_list.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        member_projects = Project.objects.filter(
            members__user=self.request.user,
            id=OuterRef('id')
        ).values('id')

        admin_projects = member_projects.filter(
            members__user=self.request.user,
            members__role='ADMIN',
            id=OuterRef('id')
        ).values('id')

        queryset = queryset.annotate(
            is_member=Subquery(member_projects),
            is_admin=Subquery(admin_projects)
        ).distinct()

        title = self.request.GET.get('title')
        priority = self.request.GET.get('priority')
        status = self.request.GET.get('status')
        deadline = self.request.GET.get('deadline')
        state = self.request.GET.get('state')

        if title:
            queryset = queryset.filter(title__icontains=title)
        if priority:
            queryset = queryset.filter(priority=priority)
        if status:
            queryset = queryset.filter(status=status)
        if deadline:
            queryset = queryset.filter(deadline__lte=deadline)
        if state:
            today = timezone.now().today()
            default_safe_date = today + timezone.timedelta(days=7)
            if state == 'delayed':
                queryset = queryset.filter(Q(deadline__lt=today) & ~Q(status='DONE'))
            elif state == 'imminent':
                queryset = queryset.filter(Q(deadline__range=(today, default_safe_date)) & ~Q(status='DONE'))
            elif state == 'plenty-time':
                queryset = queryset.filter(deadline__gt=default_safe_date)

        return queryset.order_by(Project._meta.ordering[0], '-is_admin', '-is_member')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['priorities'] = Project._meta.get_field('priority').choices
        context['status'] = Project._meta.get_field('status').choices
        context['current_time'] = timezone.now().date()
        context['imminent_time'] = timezone.now().date() + timezone.timedelta(days=7)
        return context


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = 'project_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        log_paginator = Paginator(self.object.logs.all(), 10)
        log_page_number = self.request.GET.get('log_page')
        log_page = log_paginator.get_page(log_page_number)

        comment_paginator = Paginator(self.object.comments.all(), 3)
        comment_page_number = self.request.GET.get('comment_page')
        comment_page = comment_paginator.get_page(comment_page_number)

        tasks_list = self.object.tasks.all()
        calendar_tasks = [
            {'title': task.title, 'deadline': task.deadline.strftime('%Y-%m-%d'), 'color': '#ff9f00'}
            for task in tasks_list
        ]
        calendar_tasks.append({'title': 'Fim do projeto', 'deadline': self.object.deadline.strftime('%Y-%m-%d'), 'color': '#F50101'})

        is_project_member = self.object.members.filter(user=self.request.user).exists()
        is_project_admin = self.object.members.filter(user=self.request.user, role='ADMIN').exists()

        context['log_page'] = log_page
        context['comment_page'] = comment_page
        context['calendar_tasks'] = json.dumps(calendar_tasks)
        context['is_project_member'] = is_project_member
        context['is_project_admin'] = is_project_admin
        context['current_time'] = timezone.now().date()
        context['imminent_time'] = timezone.now().date() + timezone.timedelta(days=7)
        return context


class ProjectCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'project_create.html'
    permission_required = 'projects.add_project'

    def get_success_url(self):
        return reverse_lazy('project_detail', kwargs={'pk': self.object.pk})


class ProjectUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'project_update.html'
    permission_required = 'projects.change_project'

    def has_permission(self):
        if ProjectMember.objects.filter(project=self.get_object(), user=self.request.user, role='ADMIN').exists():
            return True
        return self.request.user.has_perm(self.permission_required)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.object and self.object.deadline:
            kwargs['initial'] = {'deadline': self.object.deadline.strftime('%Y-%m-%d')}
        return kwargs

    def get_success_url(self):
        return reverse_lazy('project_detail', kwargs={'pk': self.object.pk})


class ProjectDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Project
    template_name = 'project_delete.html'
    permission_required = 'projects.delete_project'

    def get_success_url(self):
        return reverse_lazy('project_list')


class ProjectMemberCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = ProjectMember
    form_class = ProjectMemberForm
    template_name = "project_member_create.html"
    permission_required = "projects.add_projectmember"

    def get_success_url(self):
        return reverse_lazy('project_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        form.instance.project = Project.objects.get(pk=self.kwargs['pk'])
        if ProjectMember.objects.filter(user=form.instance.user, project=form.instance.project).exists():
            form.add_error('user', 'Esse usuário já está incluso no projeto.')
            return self.form_invalid(form)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = Project.objects.get(pk=self.kwargs['pk'])
        return context


class ProjectMemberUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = ProjectMember
    form_class = ProjectMemberForm
    template_name = "project_member_update.html"
    permission_required = "projects.change_projectmember"

    def get_success_url(self):
        return reverse_lazy('project_detail', kwargs={'pk': self.object.project.id})

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields.pop('user', None)
        return form


class ProjectMemberDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = ProjectMember
    template_name = "project_member_delete.html"
    permission_required = "projects.delete_projectmember"

    def get_success_url(self):
        return reverse_lazy('project_detail', kwargs={'pk': self.object.project.id})


class ProjectCommentCreateView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'projects.add_projectcomment'

    def has_permission(self):
        if ProjectMember.objects.filter(project__id=self.kwargs.get('pk'), user=self.request.user).exists():
            return True
        return self.request.user.has_perm(self.permission_required)

    def post(self, request, *args, **kwargs):
        author = request.user
        project_id = self.kwargs.get('pk')
        project = get_object_or_404(Project, pk=project_id)
        comment = request.POST.get('comment')
        if len(comment) > 0:
            ProjectComment.objects.create(
                author=author,
                project=project,
                comment=comment
            )
        return redirect('project_detail', project_id)


class ProjectCommentUpdateView(LoginRequiredMixin, PermissionRequiredMixin, View):

    def get_object(self):
        project_comment_id = self.kwargs.get('pk')
        return get_object_or_404(ProjectComment, pk=project_comment_id)

    def has_permission(self):
        project_comment = self.get_object()
        return self.request.user == project_comment.author

    def get(self, request, *args, **kwargs):
        return render(request, 'project_comment_update.html', {'object': self.get_object()})

    def post(self, request, *args, **kwargs):
        project_comment = self.get_object()
        comment = request.POST.get('comment')
        if len(comment) > 0:
            project_comment.comment = comment
            project_comment.save()
        return redirect('project_detail', project_comment.project.id)


class ProjectCommentDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = ProjectComment
    template_name = "project_comment_delete.html"
    permission_required = "projects.delete_projectcomment"

    def has_permission(self):
        project_comment = self.get_object()

projects/templates/project_comment_delete.html
{% extends 'base.html' %}

{% block title %}Deletar Comentário{% endblock %}

{% block content %}
<div class="container float-start card mb-4">
    <div class="card-body">
        <h3 class="card-title">Tem certeza que deseja deletar esse comentário?</h3>
        <p class="card-text">{{ object.comment|safe }}</p>

        <form action="{% url 'project_comment_delete' object.id %}" method="post">
            {% csrf_token %}
            <div class="d-flex gap-2">
                <button type="submit" class="btn btn-danger">Deletar</button>
                <a href="{% url 'project_detail' object.project.id %}" class="btn btn-light">Voltar para os detalhes do projeto.</a>
            </div>
        </form>
    </div> 
</div>

{% endblock %}

projects/templates/project_create.html
{% extends 'base.html' %}

{% block title %}Novo Projeto{% endblock %}

{% block content %}
<div class="container float-start card mb-4">
    <div class="card-body">
        <h3 class="card-title">Novo Projeto</h3>
        <form action="{% url 'project_create' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Criar</button>
        </form>
    </div>
</div>
<a href="{% url 'project_list' %}" class="btn btn-light">Voltar para a listagem de projetos</a>
{% endblock %}

projects/templates/project_detail.html
{% extends 'base.html' %}

{% block styles %}
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
{% endblock %}
{% block title %}Visualizar Projeto{% endblock %}

{% block content %}
<div class="container">
    <div class="card mb-4">
        <div class="card-body">
            <h3 class="card-title">
                {{ object.title }}
                {% if perms.projects.change_project or is_project_admin %}
                <a href="{% url 'project_update' object.id %}" class="btn btn-warning btn-sm"><i
                        class="bi bi-pen"></i></a>
                {% endif %}
                {% if perms.projects.delete_project %}
                <a href="{% url 'project_delete' object.id %}" class="btn btn-danger btn-sm"><i
                        class="bi bi-trash"></i></a>
                {% endif %}
            </h3>
            <p class="card-text"><strong>Status: </strong>{{ object.get_status_display }}</p>
            <p class="card-text">
                <strong>Prioridade: </strong><span class="badge {% if object.priority == 'HIGH'%}text-bg-danger{% elif object.priority == 'MEDIUM'%}text-bg-warning{% else %}text-bg-info{% endif %}">{{ object.get_priority_display }}</span></p>
            <p class="card-text"><strong>Criado em: </strong>{{ object.created_at.date }}</p>
            <p class="card-text"><strong>Prazo: </strong>
                {{ object.deadline }}
                {% if object.deadline < current_time %}
                    <span title="Atrasado"><i class="bi bi-exclamation-triangle-fill text-danger"></i></span>
                {% elif object.deadline <= imminent_time %}
                    <span title="Iminente"><i class="bi bi-exclamation-circle text-warning"></i></span>
                {% endif %}
            </p>
            <p class="card-text"><strong>Descrição: </strong>{{ object.description }}</p>
        </div>
    </div>
    {% if perms.projects.view_project or is_project_member %}
    <h5 class="fs-5 d-flex align-items-center gap-1">
        Tarefas
        <span class="badge text-bg-secondary rounded-pill">{{ object.tasks.all|length }}</span>
        {% if perms.tasks.add_task or is_project_admin %}
        {% if object.status != "DONE" %}
        <a href="{% url 'project_task_create' object.id %}" class="btn btn-info btn-sm"><i class="bi bi-plus"></i></a>
        {% endif %}
        {% endif %}
    </h5>
    <div>
        {% if object.tasks.all %}
        <section class="table-responsive">
            <table class="table table-bordered">
                <caption>Tarefas do Projeto</caption>
                <thead>
                    <tr class="table-info">
                        <th scope="col">Título</th>
                        <th scope="col">Prioridade</th>
                        <th scope="col">Status</th>
                        <th scope="col">Prazo</th>
                        <th scope="col">Número de Responsáveis</th>
                        <th scope="col">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in object.tasks.all %}
                    <tr class="{% if task.status == 'DONE' %}table-success table-active{% endif %}">
                        <td>{{ task.title }}
                            {% if task.status != 'DONE' %}
                            {% if task.deadline < current_time %}
                                <span title="Atrasado"><i class="bi bi-exclamation-triangle-fill text-danger"></i></span>
                            {% elif task.deadline <= imminent_time %}
                                <span title="Iminente"><i class="bi bi-exclamation-circle text-warning"></i></span>
                            {% endif %}
                            {% endif %}
                        </td>
                        <td class="{% if task.priority == 'HIGH'%}table-danger{% elif task.priority == 'MEDIUM'%}table-warning{% else %}table-info{% endif %}">{{ task.get_priority_display|safe }}</td>
                        <td>{{ task.get_status_display|safe }}</td>
                        <td>{{ task.deadline|date:"SHORT_DATE_FORMAT" }}</td>
                        <td>{{ task.responsible_people.all|length }} {% if user in task.responsible_people.all %} <span class="badge text-bg-success">Responsável</span>{%endif%}</td>
                        <td>
                            <a href="{% url 'task_detail' task.id %}" class="btn btn-info btn-sm"><i
                                    class="bi bi-eye"></i></a>
                            {% if perms.tasks.change_task or is_project_admin %}
                            <a href="{% url 'task_update' task.id %}" class="btn btn-warning btn-sm"><i
                                    class="bi bi-pen"></i></a>
                            {% endif %}
                            {% if perms.tasks.delete_task or is_project_admin %}
                            <a href="{% url 'task_delete' task.id %}" class="btn btn-danger btn-sm"><i
                                    class="bi bi-trash"></i></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </section>
        <div id="calendar" class="mx-auto mb-5"></div>
        {% else %}
        <p>Não há tarefas registradas para este projeto.</p>
        {% endif %}
    </div>

    

    {% if object.documents.all %}
    <h5 class="fs-5 d-flex align-items-center gap-1">
        Documentos
        <span class="badge text-bg-secondary rounded-pill">{{ object.documents.all|length }}</span>
    </h5>
    <div class="mb-4">
        <ul class="list-group">
            {% for document in object.documents.all %}
            <li class="list-group-item">
                <div class="card-body">
                    <h6 class="card-title">
                        <a href="{{ document.file.url }}">{{ document.name }}</a>
                    </h6>
                    <p class="card-text">{{ document.description}}</p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    
    <h5 class="fs-5 d-flex align-items-center gap-1">
        Membros
        <span class="badge text-bg-secondary rounded-pill">{{ object.members.all|length }}</span>
        {% if perms.projects.add_projectmember %}
        <a href="{% url 'project_member_create' object.id %}" class="btn btn-info btn-sm"><i class="bi bi-plus"></i></a>
        {% endif %}
    </h5>
    {% if object.members.all %}
    <div class="mb-4">
        <ul class="list-group">
            {% for member in object.members.all %}
            <li class="list-group-item d-flex justify-content-between">
                <span>{{ member.user.username }} <span
                        class="badge {% if member.role == 'ADMIN' %}text-bg-info{% else %}text-bg-secondary{% endif %}">{{ member.get_role_display|safe }}</span></span>
                <span>
                    {% if perms.projects.change_projectmember %}
                    <a href="{% url 'project_member_update' member.id %}" class="btn btn-warning btn-sm">
                        <i class="bi bi-pen"></i>
                    </a>
                    {% endif %}
                    {% if perms.projects.delete_projectmember %}
                    <a href="{% url 'project_member_delete' member.id %}" class="btn btn-danger btn-sm">
                        <i class="bi bi-trash"></i>
                    </a>
                    {% endif %}
                </span>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% else %}
    <p>Esse projeto ainda não tem nenhum membro associado.</p>
    {% endif %}

    <h5 class="fs-5 d-flex align-items-center gap-1">
        Comentários
        <span class="badge text-bg-secondary rounded-pill">{{ object.comments.all|length }}</span>
        <button class="btn btn-info btn-sm" id="show-comment-container"><i class="bi bi-plus"></i></button>
    </h5>

    <div id="comment-container" class="d-none">
        <form action="{% url 'project_comment_create' object.id %}" method="post" class="mb-3" id="new_comment_form">
            {% csrf_token %}
            <div id="new_comment_div" class="mb-2"></div>
            <input type="hidden" name="comment" id="comment">
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-success">Enviar comentário</button>
            </div>

        </form>
    </div>
    {% if object.comments.all %}

    <div class="mb-3 py-2 px-3" id="comment_page">
    {% for comment in comment_page %}
    
        <div class="card mb-3">
            <div class="d-flex justify-content-between align-items-center card-header">
                <h6 class="card-title m-0">
                    {{ comment.author }} {% if comment.created_at != comment.updated_at %} <span class="text-muted">(Editado
                        há {{ comment.updated_at|timesince }})</span>{% endif %}
                </h6>
                <p class="m-0">
                    {% if comment.author == user %}
                    <a href="{% url 'project_comment_update' comment.id %}" class="btn btn-warning btn-sm">
                        <i class="bi bi-pen"></i>
                    </a>
                    {% endif %}
                    {% if comment.author == user or perms.projects.delete_projectcomment %}
                    <a href="{% url 'project_comment_delete' comment.id %}" class="btn btn-danger btn-sm">
                        <i class="bi bi-trash"></i>
                    </a>
                    {% endif %}
            
                    {{ comment.created_at }}
                </p>
            
            </div>
            <div class="card-body">
                <p class="card-text">{{ comment.comment|safe }}</p>
            </div>
        </div>

    
    {% endfor %}
    </div>
    {% if comment_page.paginator.num_pages > 1 %}
    {% include 'components/_pagination.html' with page_obj=comment_page page_name='comment_page' %}
    {% endif %}
    {% else %}
    <p>Esse projeto ainda não tem comentários.</p>
    {% endif %}

    {% if perms.projects.view_projectlog or is_project_admin %}
    {% if object.logs.all %}
    <h5 class="fs-5 d-flex align-items-center gap-1" id="log_page">
        Histórico de Alterações
        <span class="badge text-bg-secondary rounded-pill">{{ object.logs.all|length }}</span>
    </h5>
    <div class="mb-4">
        <ul class="list-group mb-3">
            {% for log in log_page %}
            <li class="list-group-item d-flex justify-content-between">
                <span>{{ log.description }}</span>
                <small class="text-muted">{{ log.created_at }}</small>
            </li>
            {% endfor %}
        </ul>
        {% if log_page.paginator.num_pages > 1 %}
        {% include 'components/_pagination.html' with page_obj=log_page page_name='log_page' %}
        {% endif %}
    </div>
    {% endif %}
    {% endif %}

    {% endif %}
</div>

<a href="{% url 'project_list' %}" class="btn btn-light">Voltar para a listagem de projetos</a>

{% endblock %}

{% block scripts %}
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.js'></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const quill = new Quill('#new_comment_div', {
            theme: 'snow',
            modules: {
                toolbar: [
                    [{ 'header': [1, 2, false] }],
                    ['bold', 'italic', 'underline'],
                    ['link'],
                    ['clean']
                ]
            }
        });

        document.querySelector('#show-comment-container').addEventListener('click', () => {
            document.querySelector('#comment-container').classList.toggle('d-none')
        })

        const commentForm = document.querySelector('#new_comment_form')

        commentForm.addEventListener('submit', () => {
            document.querySelector('#comment').value = quill.root.innerHTML
        })

        const calendarElement = document.querySelector('#calendar')
        const calendarTasks =  JSON.parse('{{ calendar_tasks|safe }}')
        const calendarEvents = calendarTasks.map(task => {
            return {
                title: task.title,
                start: task.deadline,
                allDay: true,
                color: task.color
            }
        })

        const calendar = new FullCalendar.Calendar(calendarElement, {
            initialView: 'dayGridMonth',
            events: calendarEvents,
            aspectRatio: 4,
            locale: 'pt-br',
            buttonText: {
                today: 'Hoje'
            }
        })
        calendar.render()
    })


</script>
{% endblock %}