core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('api/v1/auth/', include('authentication.urls')),

    path('', views.home, name="home"),
    path('', include('projects.urls')),
    path('', include('documents.urls')),
    path('', include('tasks.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documents/models.py
from django.db import models


class Document(models.Model):
    name = models.CharField(max_length=200)
    file = models.FileField(upload_to='docs/')
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

projects/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils import timezone
from django.contrib.auth.models import User
from documents.models import Document
from core import constants


class Project(models.Model):
    title = models.CharField(max_length=500)
    description = models.TextField(blank=True, null=True)
    documents = models.ManyToManyField(Document, related_name='projects', blank=True)
    priority = models.CharField(max_length=50, choices=constants.PRIORITY_CHOICES)
    status = models.CharField(max_length=50, choices=constants.STATUS_CHOICES)
    deadline = models.DateField(validators=[
        MinValueValidator(timezone.now().date(), 'A data de término deve ser maior que a data atual.')
    ])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = [
            models.Case(
                models.When(status='DONE', then=models.Value(1)),
                models.When(status='TO_DO', then=models.Value(0)),
                models.When(status='PAUSED', then=models.Value(0)),
                models.When(status='DEVELOPING', then=models.Value(0)),
                output_field=models.IntegerField(),
            ), 'deadline', 'title']

    def __str__(self):
        return self.title


class ProjectMember(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="projects")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="members")
    role = models.CharField(max_length=50, choices=constants.ROLE_CHOICES)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'project'], name='unique_user_project')
        ]
        ordering = [models.Case(
            models.When(role='ADMIN', then=0),
            models.When(role='MEMBER', then=1),
            default=2,
            output_field=models.IntegerField()
        )]

    def __str__(self):
        return self.user.username


class ProjectComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="project_comments")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.author.username


class ProjectLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="project_logs")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="logs")
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.project.title

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.utils import timezone
from projects.models import Project
from core import constants


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="tasks")
    responsible_people = models.ManyToManyField(User, related_name="tasks", blank=True)
    title = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    priority = models.CharField(max_length=50, choices=constants.PRIORITY_CHOICES)
    status = models.CharField(max_length=50, choices=constants.STATUS_CHOICES)
    deadline = models.DateField(validators=[
        MinValueValidator(timezone.now().date(), 'A data de término deve ser maior que a data atual.')
    ])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = [
            models.Case(
                models.When(status='DONE', then=models.Value(1)),
                models.When(status='TO_DO', then=models.Value(0)),
                models.When(status='PAUSED', then=models.Value(0)),
                models.When(status='DEVELOPING', then=models.Value(0)),
                output_field=models.IntegerField(),
            ), 'deadline', 'title']

    def __str__(self):
        return self.title

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from . import metrics


@login_required
def home(request):
    context = {
        'total_projects_by_status': metrics.get_total_projects_by_status(),
        'total_projects_by_priority': metrics.get_total_projects_by_priority(),
        'daily_total_projects_logs': metrics.get_daily_total_projects_logs(),
        'total_delayed_projects': metrics.get_total_delayed_projects(),
        'total_imminent_projects': metrics.get_total_imminent_projects(),

        'total_tasks_by_status': metrics.get_total_tasks_by_status(),
        'total_tasks_by_priority': metrics.get_total_tasks_by_priority(),
        'total_delayed_tasks': metrics.get_total_delayed_tasks(),
        'total_imminent_tasks': metrics.get_total_imminent_tasks(),
        'projects_with_most_pending_tasks': metrics.get_projects_with_most_pending_tasks(),

        'total_docs': metrics.get_total_docs(),
        'most_used_docs': metrics.get_most_used_docs(),
        'less_used_docs': metrics.get_less_used_docs(),

        'calendar_data': metrics.get_calendar_data()
    }

    return render(request, 'home.html', context)

core/templates/base.html
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% block styles %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% include 'components/_header.html' %}
    <div class="container-fluid">
        <div class="row flex-nowrap">
            {% if user.is_authenticated %}
            {% include 'components/_sidebar.html' %}
            {% endif %}
            <main class="col py-3">
                {% block content %}
                {% endblock content %}
            </main>
        </div>
    </div>

    {% include 'components/_footer.html' %}
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

core/templates/home.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="row justify-content-between align-items-center">
    <div class="col-md-6 col-12">
        <h1>Bem-vindo(a) ao SGP!</h1>
    </div>
    {% if perms.projects.view_project %}
    <div class="col-md-6 col-12 d-flex justify-content-end">
        <button class="btn btn-primary show-calendar-btn">Mostrar calendário</button>
    </div>
</div>

<div class="my-3">
    <div class="container">
        <div id="calendar" class="my-2"></div>
    </div>
</div>
{% include 'components/_projects_metrics.html' %}
<div class="mb-5"></div>
{% endif %}

{% if perms.tasks.view_task %}
{% include 'components/_tasks_metrics.html' %}
<div class="mb-5"></div>
{% endif %}

{% if perms.documents.view_document %}
{% include 'components/_docs_metrics.html' %}
{% endif %}

{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

{% if perms.projects.view_project %}
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.js'></script>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        const calendarElement = document.querySelector('#calendar')
        const calendarData =  JSON.parse('{{ calendar_data|safe }}')
        const calendarEvents = calendarData.map(data => {
            return {
                title: data.title,
                start: data.deadline,
                allDay: true,
                color: data.color
            }
        })

        const calendar = new FullCalendar.Calendar(calendarElement, {
            initialView: 'dayGridMonth',
            events: calendarEvents,
            aspectRatio: 2,
            locale: 'pt-br',
            buttonText: {
                today: 'Hoje'
            }
        })
        calendar.render()

        // Don't add the class 'd-none' directly in the HTML element, because it bugs the calendar render.
        calendarElement.parentNode.classList.add('d-none')

        const showCalendarBtn = document.querySelector('.show-calendar-btn')
        showCalendarBtn.addEventListener('click', ()=>{
            if(calendarElement.parentNode.classList.contains('d-none')){
                calendarElement.parentNode.classList.remove('d-none')
                showCalendarBtn.textContent = 'Fechar calendário'
            } else {
                calendarElement.parentNode.classList.add('d-none')
                showCalendarBtn.textContent = 'Mostrar calendário'
            }
        })
    })


</script>
{% endif %}
{% endblock %}